version: '3'

services:

  web:
    image: nginx:latest
    container_name: 'nginx'
    ports:
        - 9099:80
    volumes:
        - ../source/:/var/www/html
        - ./microServices/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
    networks:
      - app-network

  php:
    build: microServices/phpfpm
    container_name: 'phpfpm'
#    command: --storage-driver=overlay
    volumes:
        - ../source/:/var/www/html
    networks:
      - app-network
  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: edfa3ly
      MYSQL_USER: khaled
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

networks:
  app-network:
    driver: "bridge"

volumes:
  dbdata:
    driver: local